# Lab01-2 Tensor Manipulation 2

In [1]:
import numpy as np
import torch

In [3]:
t = np.array([[[1, 2, 3], 
               [5, 7, 9]], 
               
               [[8, 3, 5],
               [0, 4, 6]]])
ft = torch.FloatTensor(t)
print(ft.shape)
# |ft| = (2, 2, 3)

torch.Size([2, 2, 3])


In [4]:
print(ft.view([-1, 3])) # reshape
print(ft.view([-1, 3]).shape)
# |ft| = (2x2, 3) = (4, 3)

tensor([[1., 2., 3.],
        [5., 7., 9.],
        [8., 3., 5.],
        [0., 4., 6.]])
torch.Size([4, 3])


In [5]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)
# |ft| = (2x2, 1, 3) = (4, 1, 3)

tensor([[[1., 2., 3.]],

        [[5., 7., 9.]],

        [[8., 3., 5.]],

        [[0., 4., 6.]]])
torch.Size([4, 1, 3])


## Squeeze

In [6]:
# Squeeze

ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [7]:
# remove (# of dim == 1)
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze

#

In [8]:
# Unsqueeze
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [16]:
# n차원에 dim 1을 추가 : unsqueeze(n)
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [10]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [11]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [12]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type Casting

In [17]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [18]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [19]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [20]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## Concatenate

In [21]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [22]:
print(torch.cat([x, y], dim = 0))
print(torch.cat([x, y], dim = 1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking

In [23]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [24]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim = 1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [25]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones and Zeros

In [26]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)
# |x| = (2, 3)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [27]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place Operation

In [28]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [29]:
print(x.mul(2.))
print(x)
print(x.mul_(2.)) # in-place 정답값을 기존의 tensor에 넣는다
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
