# Lab 01-1 Tensor Manipulation 1

In [1]:
import numpy as np
import torch

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # element
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1]) # slicing
print('t[:2] t[3:]     = ', t[:2], t[3:]) # slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [5]:
# 2D array with numpy
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


In [7]:
# 1D array with Pytorch
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [8]:
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape
print(t[0], t[1], t[-1]) # element
print(t[2:5], t[4:-1]) # slicing
print(t[:2], t[3:]) # slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [9]:
# 2D array with pyTorch
t = torch.FloatTensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim()) # rank
print(t.size()) # shape
print(t[:, 1])
print(t[:, 1].size()) 
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Broadcasting

In [12]:
# same shape
# |m1| = (1, 2)
# |m2| = |m1|
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [13]:
# vector + scalar
# |m1| = (1, 2)
# |m2| = (1, ) -> (1, 2)
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [15]:
# 2 x 1 vector + 1 x 2 vector
# |m1| = (1, 2) -> (2, 2)
# |m2| = (2, 1) -> (2, 2)
m1 = torch.FloatTensor([[1, 7]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[ 4., 10.],
        [ 5., 11.]])


In [17]:
print()
print('--------------------------')
print('Mat vs Matmul')
print('--------------------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of matrix 1: ', m1.shape) # 2 x 2
print('Shape of matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of matrix 1: ', m1.shape) # 2 x 2
print('Shape of matrix 2: ', m2.shape) # 2 x 1 -> 2 x 2 ( Broadcasting )
print(m1 * m2) # 2 x 2 # Hadamard Product
print(m1.mul(m2))


--------------------------
Mat vs Matmul
--------------------------
Shape of matrix 1:  torch.Size([2, 2])
Shape of matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of matrix 1:  torch.Size([2, 2])
Shape of matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [18]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [19]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2]) # integer tensor
try:
  print(t.mean())
except Exception as exc:
  print(exc)

Can only calculate the mean of floating types. Got Long instead.


You can also use $t.mean$ for higher rank tensors to get mean of all elements, or mean by particular dimension

In [20]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [21]:
print(t.mean())
print(t.mean(dim = 0)) # column을 합침
print(t.mean(dim = 1)) # row를 합침
print(t.mean(dim = -1)) 

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [23]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [24]:
print(t.sum())
print(t.sum(dim = 0))
print(t.sum(dim = 1))
print(t.sum(dim = -1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [36]:
t = torch.FloatTensor([[1, 10], [100, 3]])
print(t)

tensor([[  1.,  10.],
        [100.,   3.]])


The $max$ operator returns one value if it is called without an argument

In [37]:
print(t.max())

tensor(100.)


The $max$ operator returns 2 values when called with dimension specified.
The first value is the maximum value, and the second value is the argmax: the index of element with maximum value.

In [38]:
print(t.max(dim = 0))
print('Max : ', t.max(dim = 0)[0])
print('Argmax : ', t.max(dim = 0)[1])

torch.return_types.max(
values=tensor([100.,  10.]),
indices=tensor([1, 0]))
Max :  tensor([100.,  10.])
Argmax :  tensor([1, 0])


In [39]:
print(t.max(dim = 1))
print(t.max(dim = -1))

torch.return_types.max(
values=tensor([ 10., 100.]),
indices=tensor([1, 0]))
torch.return_types.max(
values=tensor([ 10., 100.]),
indices=tensor([1, 0]))
